name: Code Test
on:
  workflow_dispatch:
  #push:
  #  branches: [ "master" ]

jobs:
  python_test:
    runs-on: ubuntu-latest
    name: Pytest summary
    steps:
      - uses: actions/checkout@v3
      - name: Execute Pytest
        run: |
          pytest -v
          #echo "Hello PyTest!"
