# This is a basic workflow to help you get started with Actions

name: Code Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  python_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Pytest summary
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
            
        # You may pin to the exact commit or the version.
        # uses: dariocurr/pytest-summary@9cdbcd0634fade9eb80209e687508b876be804fc
      - name: Execute Pytest
        uses: dariocurr/pytest-summary@v1
        with:
          # The pytest extensions to install along pytest
          #extensions: # optional
          # The pytest options
          #options: # optional
          # The path to the output file to create
          #output: # optional
          # The path to the folder containing the tests
          path: . 
          # Which tests have to be shown in the summary
          #show: # optional
